apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-utils
  labels:
    app: cluster-utils
    purpose: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-utils
  template:
    metadata:
      labels:
        app: cluster-utils
    spec:
      containers:
        - name: cluster-utils
          #image: ghcr.io/donkeyx/cluster-utils:latest
          image: donkeyx/cluster-utils:latest
          # Remove RUNTIME env if it was only for timeout
      restartPolicy: Always
