apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-utils
  labels:
    app: cluster-utils
    purpose: testing
spec:
  template:
    spec:
      containers:
        - name: cluster-utils
          image: donkeyx/cluster-utils:latest
          env:
            - name: RUNTIME
              value: "1800"
      restartPolicy: Never
  ttlSecondsAfterFinished: 1800
