apiVersion: v1
kind: Pod
metadata:
  name: cluster-utils
  labels:
    app: cluster-utils
    purpose: testing
spec:
  containers:
    - name: cluster-utils
      image: donkeyx/cluster-utils:latest
      env:
        - name: RUNTIME
          value: "1800"
  restartPolicy: Never
