name: Docker build and push

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      # - name: Login to Docker Hub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v3
      #   with:
      #     # username: ${{ vars.DOCKERHUB_USERNAME }}
      #     # password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     username: "${{ vars.DOCKERHUB_USERNAME }}"
      #     password: "${{ secrets.DOCKERHUB_TOKEN }}"
      #     logout: true

      - name: testing
        run: echo asdfadsf| docker login -u donkeyx --password-stdin
