name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    environment: deployment # this gets the secrets for deployments

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ################################
      # create release and push assets 
      # ################################ 
      - name: Build go binaries
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make build-all

      - name: Release to github with Notes
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          generate_release_notes: true

        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
